-- ZinaRaidbotsData.lua — ZinaGearCompare
-- Per-item DPS data from Raidbots Top Gear simulations.
-- Generated by tools/raidbots_import.py — 2026-03-24 13:54
-- DO NOT EDIT MANUALLY — re-run the script to update.

ZGC_RaidbotsData = ZGC_RaidbotsData or {}

ZGC_RaidbotsData["aoe"] = {
    character = "Zínashari",
    class     = "druid",
    spec      = "feral",
    reportID  = "3sGG5PW9wuHwSCAmAiQf5m",
    specID    = 103,
    specName  = "Feral Druid",
    fightStyle = "DungeonSlice",
    imported  = "2026-03-24 13:54",
    bestComboDPS   = 65099.6,
    currentGearDPS = 48378.5,
    baselineDPS    = 65099.6,

    items = {
        [151317] = { name="Footpads of Seeping Dread", ilvl=246, slot="feet", avgDPS=56750.5, delta=0.0, n=24 },
        [240951] = { name="Thalassian Competitor's Signet", ilvl=246, slot="finger2", avgDPS=56828.1, delta=0.0, n=16 },
        [249314] = { name="Twisted Twilight Sash", ilvl=250, slot="waist", avgDPS=56708.3, delta=0.0, n=24 },
        [251115] = { name="Bifurcation Band", ilvl=250, slot="finger2", avgDPS=56621.1, delta=-207.0, n=8 },
        [251194] = { name="Lightwarden's Bind", ilvl=250, slot="finger2", avgDPS=56640.1, delta=-188.0, n=24 },
        [251210] = { name="Eclipse Espadrilles", ilvl=246, slot="feet", avgDPS=56648.7, delta=-101.8, n=24 },
        [251217] = { name="Occlusion of Void", ilvl=246, slot="finger1", avgDPS=56560.2, delta=-330.2, n=24 },
        [263267] = { name="Hara'ti Defender's Cord", ilvl=250, slot="waist", avgDPS=56691.0, delta=-17.3, n=24 },
    },

    bestBySlot = {
        ["feet"] = { id=151317, name="Footpads of Seeping Dread", avgDPS=56750.5 },
        ["finger1"] = { id=240951, name="Thalassian Competitor's Signet", avgDPS=56890.4 },
        ["finger2"] = { id=240951, name="Thalassian Competitor's Signet", avgDPS=56828.1 },
        ["waist"] = { id=249314, name="Twisted Twilight Sash", avgDPS=56708.3 },
    },
}

ZGC_RaidbotsData["st"] = {
    character = "Zínashari",
    class     = "druid",
    spec      = "feral",
    reportID  = "ua7Weq6gv5UmNEnhLwAf37",
    imported  = "2026-03-24 13:16",
    bestComboDPS   = 56530.8,
    currentGearDPS = 56435.5,
    baselineDPS    = 56530.8,

    items = {
        [251096] = { name="Pendant of Aching Grief", ilvl=246, slot="neck", avgDPS=56340.2, delta=-89.1, n=16 },
        [251103] = { name="Custodial Cuffs", ilvl=240, slot="wrist", avgDPS=56366.4, delta=-36.7, n=16 },
        [251109] = { name="Spellsnap Shadowmask", ilvl=246, slot="head", avgDPS=56328.1, delta=-113.2, n=16 },
        [251135] = { name="Fury-fletched Armlets", ilvl=240, slot="wrist", avgDPS=56403.1, delta=0.0, n=16 },
        [251161] = { name="Soulhunter's Mask", ilvl=246, slot="back", avgDPS=56333.0, delta=-73.0, n=8 },
        [251206] = { name="Fluxweave Cloak", ilvl=246, slot="back", avgDPS=56406.0, delta=0.0, n=8 },
        [257174] = { name="Voidbreaker's Mantle", ilvl=246, slot="back", avgDPS=56395.1, delta=-10.9, n=8 },
        [258575] = { name="Rigid Scale Greatcloak", ilvl=246, slot="back", avgDPS=56405.0, delta=-1.0, n=8 },
        [265739] = { name="Amani Heartstring Pendant", ilvl=246, slot="neck", avgDPS=56429.3, delta=0.0, n=16 },
        [266430] = { name="Silvermoon Sunguard", ilvl=246, slot="head", avgDPS=56441.4, delta=0.0, n=16 },
    },

    bestBySlot = {
        ["back"] = { id=251206, name="Fluxweave Cloak", avgDPS=56406.0 },
        ["head"] = { id=266430, name="Silvermoon Sunguard", avgDPS=56441.4 },
        ["neck"] = { id=265739, name="Amani Heartstring Pendant", avgDPS=56429.3 },
        ["wrist"] = { id=251135, name="Fury-fletched Armlets", avgDPS=56403.1 },
    },
}
