-- ZinaRaidbots.lua — ZinaGearCompare
-- Reads ZinaRaidbotsData.lua (generated by tools/raidbots_import.py)
-- and displays per-item DPS deltas in item tooltips + bag upgrade icons.
-- Only active when the player's current spec matches the imported sim spec.

local ADDON_NAME = "ZinaGearCompare"

-- ── Spec guard ──────────────────────────────────────────────────────────────

--- Get the player's current specID.
local function GetPlayerSpecID()
    local idx = GetSpecialization and GetSpecialization()
    if idx and GetSpecializationInfo then
        return (GetSpecializationInfo(idx))
    end
    return nil
end

--- Check if a sim data block matches the player's current spec.
local function IsSimForCurrentSpec(d)
    if not d or not d.specID or d.specID == 0 then return true end -- no guard if unknown
    local playerSpec = GetPlayerSpecID()
    return playerSpec == d.specID
end

--- Check if ANY Raidbots data matches current spec.
local function HasDataForCurrentSpec()
    if not ZGC_RaidbotsData then return false end
    for _, key in ipairs({"st", "aoe"}) do
        local d = ZGC_RaidbotsData[key]
        if d and IsSimForCurrentSpec(d) then return true end
    end
    return false
end

-- ── Lookup helpers ──────────────────────────────────────────────────────────

local function GetItemIDFromLink(link)
    if not link then return nil end
    local id = link:match("item:(%d+)")
    return id and tonumber(id) or nil
end

local function GetSimKey()
    local ct = ZGC_GetContentType and ZGC_GetContentType() or "dungeon"
    return ct == "raid" and "st" or "aoe"
end

local function LookupItem(itemID)
    if not ZGC_RaidbotsData or not itemID then return nil, nil end
    local stData  = ZGC_RaidbotsData.st
    local aoeData = ZGC_RaidbotsData.aoe
    local stInfo  = stData  and IsSimForCurrentSpec(stData)  and stData.items  and stData.items[itemID]
    local aoeInfo = aoeData and IsSimForCurrentSpec(aoeData) and aoeData.items and aoeData.items[itemID]
    return stInfo, aoeInfo
end

local function IsItemBIS(itemID)
    if not ZGC_RaidbotsData or not itemID then return false end
    local key = GetSimKey()
    local d = ZGC_RaidbotsData[key]
    if not d or not d.bestBySlot then return false end
    if not IsSimForCurrentSpec(d) then return false end
    for _, info in pairs(d.bestBySlot) do
        if info.id == itemID then return true end
    end
    return false
end

local function GetShortDate(key)
    if not ZGC_RaidbotsData then return nil end
    local d = ZGC_RaidbotsData[key]
    if not d or not d.imported then return nil end
    local y, m, day = d.imported:match("(%d+)-(%d+)-(%d+)")
    if not m then return d.imported end
    local months = {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"}
    return (months[tonumber(m)] or m) .. " " .. (tonumber(day) or day)
end

local function GetFullDate(key)
    if not ZGC_RaidbotsData then return nil end
    local d = ZGC_RaidbotsData[key]
    if not d or not d.imported then return nil end
    local y, m, day, hour, min = d.imported:match("(%d+)-(%d+)-(%d+)%s+(%d+):(%d+)")
    if not m then return d.imported end
    local months = {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"}
    return string.format("%s %s %s:%s", months[tonumber(m)] or m, tonumber(day) or day, hour, min)
end

-- ── Tooltip formatting ──────────────────────────────────────────────────────

local function FormatPctActive(delta, baseline)
    if not baseline or baseline == 0 then return "" end
    local pct = (delta / baseline) * 100
    if delta > 0 then
        return string.format("|cff00ff00+%.2f%%|r", pct)
    elseif delta < 0 then
        return string.format("|cffff3333%.2f%%|r", pct)
    else
        return "|cff00ff00BEST|r"
    end
end

local function FormatPctDimmed(delta, baseline)
    if not baseline or baseline == 0 then return "" end
    local pct = (delta / baseline) * 100
    if delta > 0 then
        return string.format("|cff77bb77+%.2f%%|r", pct)
    elseif delta < 0 then
        return string.format("|cffbb7777%.2f%%|r", pct)
    else
        return "|cff77bb77BEST|r"
    end
end

local function AddSimLine(tooltip, label, info, isActive, dateStr)
    if not info then return end
    local baseline = info.baseline or 0
    local prefix, value
    if isActive then
        prefix = "|cff00aaff" .. label .. ":|r "
        value  = FormatPctActive(info.delta, baseline)
    else
        prefix = "|cff999999" .. label .. ":|r "
        value  = FormatPctDimmed(info.delta, baseline)
    end
    local datePart = dateStr and ("  |cff777777(" .. dateStr .. ")|r") or ""
    tooltip:AddLine(prefix .. value .. datePart)
end

-- ── Item tooltip hook ───────────────────────────────────────────────────────

local function OnTooltipSetItem(tooltip, data)
    if not ZGC_RaidbotsData then return end
    if not data then return end
    if not HasDataForCurrentSpec() then return end

    local itemID
    if data.id then
        itemID = data.id
    elseif tooltip.GetItem then
        local _, link = tooltip:GetItem()
        itemID = GetItemIDFromLink(link)
    end
    if not itemID then return end

    local stInfo, aoeInfo = LookupItem(itemID)
    if not stInfo and not aoeInfo then return end

    if stInfo and ZGC_RaidbotsData.st then
        stInfo = { delta = stInfo.delta, baseline = ZGC_RaidbotsData.st.baselineDPS }
    end
    if aoeInfo and ZGC_RaidbotsData.aoe then
        aoeInfo = { delta = aoeInfo.delta, baseline = ZGC_RaidbotsData.aoe.baselineDPS }
    end

    local activeKey = GetSimKey()
    local showDate = not ZGC_GetAppearance or ZGC_GetAppearance("showTooltipDate")
    if not ZGC_GetAppearance or ZGC_GetAppearance("showTooltipST") then
        AddSimLine(tooltip, "Raidbots ST",  stInfo,  activeKey == "st",  showDate and GetShortDate("st"))
    end
    if not ZGC_GetAppearance or ZGC_GetAppearance("showTooltipAoE") then
        AddSimLine(tooltip, "Raidbots AoE", aoeInfo, activeKey == "aoe", showDate and GetShortDate("aoe"))
    end
    tooltip:Show()
end

-- ── Bag upgrade overlay ─────────────────────────────────────────────────────

local ZGC_GLOW_KEY = "ZGCRaidbotsGlow"

local function GetOrCreateGlow(button)
    if button[ZGC_GLOW_KEY] then return button[ZGC_GLOW_KEY] end

    local glow = button:CreateTexture(nil, "OVERLAY", nil, 2)
    glow:SetTexture("Interface\\Buttons\\UI-ActionButton-Border")
    glow:SetBlendMode("ADD")
    glow:SetVertexColor(0.1, 1.0, 0.1, 0.9)
    local w, h = button:GetSize()
    glow:SetSize(w * 1.6, h * 1.6)
    glow:ClearAllPoints()
    glow:SetPoint("CENTER", button, "CENTER", 0, 0)
    glow:Hide()

    button[ZGC_GLOW_KEY] = glow
    return glow
end

local function UpdateItemButtonUpgrade(button)
    if not button then return end

    local show = false
    local glowEnabled = not ZGC_GetAppearance or ZGC_GetAppearance("showBagGlow")
    if glowEnabled and HasDataForCurrentSpec() then
        local bagID  = (button.GetBagID and button:GetBagID())
                    or (button:GetParent() and button:GetParent().GetID and button:GetParent():GetID())
        local slotID = button.GetID and button:GetID()

        if bagID and slotID and button:IsShown() then
            local ok, itemInfo = pcall(C_Container.GetContainerItemInfo, bagID, slotID)
            if ok and itemInfo and itemInfo.hyperlink then
                local itemID = GetItemIDFromLink(itemInfo.hyperlink)
                if itemID and IsItemBIS(itemID) then
                    show = true
                end
            end
        end
    end

    local glow = button[ZGC_GLOW_KEY]
    if show then
        glow = glow or GetOrCreateGlow(button)
        glow:Show()
    elseif glow then
        glow:Hide()
    end
end

local function UpdateContainerFrameUpgradeIcons(containerFrame)
    if not containerFrame then return end
    if not ZGC_RaidbotsData then return end

    if containerFrame.EnumerateValidItems then
        for _, itemButton in containerFrame:EnumerateValidItems() do
            UpdateItemButtonUpgrade(itemButton)
        end
    elseif containerFrame.Items then
        for _, itemButton in pairs(containerFrame.Items) do
            if itemButton then
                UpdateItemButtonUpgrade(itemButton)
            end
        end
    end
end

local bagOverlaysInitialized = false

local function InitBagOverlays()
    if bagOverlaysInitialized then return end
    bagOverlaysInitialized = true

    if ContainerFrameMixin and ContainerFrameMixin.UpdateItems then
        hooksecurefunc(ContainerFrameMixin, "UpdateItems", UpdateContainerFrameUpgradeIcons)
    end
    if ContainerFrameCombinedBags and ContainerFrameCombinedBags.UpdateItems then
        hooksecurefunc(ContainerFrameCombinedBags, "UpdateItems", UpdateContainerFrameUpgradeIcons)
    end
    local numBags = NUM_TOTAL_BAG_FRAMES or NUM_CONTAINER_FRAMES or 13
    for i = 1, numBags do
        local bag = _G["ContainerFrame" .. i]
        if bag and bag.UpdateItems then
            hooksecurefunc(bag, "UpdateItems", UpdateContainerFrameUpgradeIcons)
        end
    end
end

-- ── Init ────────────────────────────────────────────────────────────────────

local function InitRaidbots()
    if TooltipDataProcessor then
        TooltipDataProcessor.AddTooltipPostCall(Enum.TooltipDataType.Item, OnTooltipSetItem)
    end
    pcall(InitBagOverlays)

    if ZGC_RaidbotsData then
        local count = 0
        local types = {}
        for _, key in ipairs({"st", "aoe"}) do
            local d = ZGC_RaidbotsData[key]
            if d and d.items then
                local n = 0
                for _ in pairs(d.items) do n = n + 1 end
                count = count + n
                local specTag = d.specName or ""
                table.insert(types, string.format("%s [%s]", key:upper(), specTag))
            end
        end
        if count > 0 then
            print(string.format("|cff00aaffZGC Raidbots:|r %d items loaded (%s)", count, table.concat(types, " + ")))
        end
    end
end

-- ── Public: sim info for minimap tooltip ─────────────────────────────────────

-- Map WoW inventory slot IDs to Raidbots slot names
local EQUIP_SLOT_TO_SIM = {
    [1]  = "head",    [2]  = "neck",     [3]  = "shoulder",
    [5]  = "chest",   [6]  = "waist",    [7]  = "legs",
    [8]  = "feet",    [9]  = "wrist",    [10] = "hands",
    [11] = "finger1", [12] = "finger2",
    [13] = "trinket1",[14] = "trinket2",
    [15] = "back",
    [16] = "main_hand", [17] = "off_hand",
}

local EQUIP_SLOT_LABEL = {
    [1]  = "Head",    [2]  = "Neck",     [3]  = "Shoulder",
    [5]  = "Chest",   [6]  = "Waist",    [7]  = "Legs",
    [8]  = "Feet",    [9]  = "Wrist",    [10] = "Hands",
    [11] = "Ring 1",  [12] = "Ring 2",
    [13] = "Trinket 1",[14] = "Trinket 2",
    [15] = "Back",
    [16] = "Main Hand", [17] = "Off Hand",
}

local EQUIP_SLOT_IDS = {1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17}

function ZGC_GetRaidbotsTooltipInfo()
    if not ZGC_RaidbotsData then return nil end
    local lines = {}
    for _, key in ipairs({"st", "aoe"}) do
        local d = ZGC_RaidbotsData[key]
        if d then
            local n = 0
            if d.items then for _ in pairs(d.items) do n = n + 1 end end
            local dateStr = GetFullDate(key) or "?"
            local active = IsSimForCurrentSpec(d)

            -- Collect simulated slot names from items + bestBySlot
            local simSlots = {}
            if d.items then
                for _, item in pairs(d.items) do
                    if item.slot then simSlots[item.slot] = true end
                end
            end
            if d.bestBySlot then
                for slot in pairs(d.bestBySlot) do
                    simSlots[slot] = true
                end
            end

            table.insert(lines, {
                label    = key:upper(),
                date     = dateStr,
                items    = n,
                dps      = d.bestComboDPS or d.baselineDPS or 0,
                specName = d.specName or "?",
                active   = active,
                simSlots = simSlots,
            })
        end
    end
    return #lines > 0 and lines or nil
end

--- Returns slot coverage info for the active sim type.
--- @return number simmedSlots, number equippedSlots, table unsimmedList
function ZGC_GetSlotCoverage()
    if not ZGC_RaidbotsData then return 0, 0, {} end
    local key = GetSimKey()
    local d = ZGC_RaidbotsData[key]
    if not d or not IsSimForCurrentSpec(d) then return 0, 0, {} end

    -- Collect simulated slots
    local simSlots = {}
    if d.items then
        for _, item in pairs(d.items) do
            if item.slot then simSlots[item.slot] = true end
        end
    end
    if d.bestBySlot then
        for slot in pairs(d.bestBySlot) do
            simSlots[slot] = true
        end
    end

    local equipped = 0
    local simmed = 0
    local unsimmed = {}

    for _, slotID in ipairs(EQUIP_SLOT_IDS) do
        local link = GetInventoryItemLink("player", slotID)
        if link then
            local ilvl = GetDetailedItemLevelInfo and GetDetailedItemLevelInfo(link) or 0
            if ilvl and ilvl >= 200 then
                equipped = equipped + 1
                local simName = EQUIP_SLOT_TO_SIM[slotID]
                if simName and simSlots[simName] then
                    simmed = simmed + 1
                else
                    local label = EQUIP_SLOT_LABEL[slotID] or "?"
                    local itemName = link:match("%[(.-)%]") or "?"
                    table.insert(unsimmed, {
                        label = label,
                        name  = itemName,
                        ilvl  = ilvl,
                    })
                end
            end
        end
    end

    return simmed, equipped, unsimmed
end

-- ── Slash command: /zgc raidbots ────────────────────────────────────────────

function ZGC_RaidbotsStatus()
    if not ZGC_RaidbotsData then
        print("|cff00aaffZGC Raidbots:|r No data loaded. Run tools/raidbots_import.bat and /reload.")
        return
    end
    local playerSpec = GetPlayerSpecID()
    for _, key in ipairs({"st", "aoe"}) do
        local d = ZGC_RaidbotsData[key]
        if d then
            local n = 0
            if d.items then for _ in pairs(d.items) do n = n + 1 end end
            local match = IsSimForCurrentSpec(d)
            local matchTag = match and "|cff00ff00ACTIVE|r" or "|cff888888inactive|r"
            print(string.format(
                "|cff00aaffZGC Raidbots %s:|r %s (%s) — %d items — %.0fk DPS — %s — %s",
                key:upper(), d.character or "?", d.specName or "?",
                n, (d.bestComboDPS or d.baselineDPS or 0) / 1000,
                d.imported or "?", matchTag))
        end
    end
end

-- ── Register on addon load ──────────────────────────────────────────────────

local f = CreateFrame("Frame")
f:RegisterEvent("ADDON_LOADED")
f:SetScript("OnEvent", function(self, event, addon)
    if addon == ADDON_NAME then
        InitRaidbots()
        self:UnregisterEvent("ADDON_LOADED")
    end
end)
